name = "sales-assistant-widget"
uid = "3981ab4b-a40a-9225-dc2f-219366eb75c141d17417"
type = "theme"

name = "AI Sales Assistant"
type = "theme"

[[assets]]
  key = "assets/ai-sales-assistant.js"

[[assets]]
  key = "assets/ai-sales-assistant.css"

[[snippets]]
  key = "snippets/ai-sales-assistant.liquid"